name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag detection:$(date +%s)
    - name: Save Docker image to tar
      run: docker save detection:latest -o detection.tar
    - name: Upload image tar as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: detection.tar
